# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190422_1008'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
