# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-29 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityrecommendationview',
            old_name='act_views',
            new_name='views',
        ),
    ]
