# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20190423_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='video_link',
            new_name='post',
        ),
    ]
