# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20190424_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
