# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_event_post_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-post_order', '-title']},
        ),
    ]
