# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_post_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category_example',
            field=models.CharField(choices=[('main_choice', 'Main_choice'), ('alternative_choice', 'Alternative_choice')], default='main_choice', max_length=110),
        ),
    ]
