# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_category_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
