# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_useractivities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activities', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='useractivities',
            options={'verbose_name': 'My Activities', 'verbose_name_plural': 'My Activities'},
        ),
    ]
