# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20190424_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivities',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='registered', to='activities.Activity'),
        ),
    ]
