# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('activities', '0017_auto_20190425_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_genre', to='categories.Genre'),
        ),
    ]
