# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 19:07
from __future__ import unicode_literals

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_activity_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_thumbanil',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=activities.models.handle_image_upload, width_field='image_width'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
