# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-27 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_auto_20190425_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='basic',
            field=models.BooleanField(default=False),
        ),
    ]
