# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190509_0608'),
        ('activities', '0020_event_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post'),
        ),
    ]
