# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_activity_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image_thumbanil',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='activities', width_field='image_width'),
        ),
    ]
