# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_auto_20190509_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
