# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-21 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190421_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
