# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='basic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='member',
            field=models.BooleanField(default=False),
        ),
    ]
