# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 05:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190422_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(default=1, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='embed_link',
            field=models.TextField(blank=True),
        ),
    ]
