# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190509_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link',
            new_name='social_media_link',
        ),
    ]
