# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_auto_20190509_2127'),
        ('accounts', '0005_auto_20190509_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
            preserve_default=False,
        ),
    ]
